### ISSUE TITLE
Add API to generate response defined by HTTP/2 debug state

### ISSUE THREAD

**Issue by tatsuhiro-t** [nghttp2/nghttp2#657]
https://tools.ietf.org/html/draft-benfield-http2-debug-state-01

Here is list of data it will produce, and corresponding nghttp2 API.  N/A if it is not available:
- [x] settings: nghttp2_session_get_local_settings() #664
- peerSettings: https://nghttp2.org/documentation/nghttp2_session_get_remote_settings.html
- connFlowOut: https://nghttp2.org/documentation/nghttp2_session_get_remote_window_size.html
- [x] connFlowIn: nghttp2_session_get_local_window_size() #664
- streams
  - state: https://nghttp2.org/documentation/nghttp2_stream_get_state.html
  - [x] flowIn: nghttp2_session_get_stream_local_window_size() #664
  - flowOut: https://nghttp2.org/documentation/nghttp2_session_get_stream_remote_window_size.html
  - dataIn: N/A
  - dataOut: N/A
  - paddingIn: N/A
  - paddingOut: N/A
  - queuedData: N/A
  - created: N/A
- HPACK
  - [x] inboundTableSize: nghttp2_session_get_hd_inflate_dynamic_table_size() #664
  - [x] outboundTableSize: nghttp2_session_get_hd_deflate_dynamic_table_size() #664
  - inboundDynamicHeaderTable: N/A  FYI, https://nghttp2.org/documentation/nghttp2_hd_inflate_get_num_table_entries.html and https://nghttp2.org/documentation/nghttp2_hd_inflate_get_table_entry.html
  - outboundDynamicHeaderTable: N/A  FYI, https://nghttp2.org/documentation/nghttp2_hd_deflate_get_num_table_entries.html and https://nghttp2.org/documentation/nghttp2_hd_deflate_get_table_entry.html
- sentGoAway: N/A

**Comment by tatsuhiro-t** [comment]
#664 will add flow control related APIs.

**Comment by tatsuhiro-t** [comment]
Focus on required fields first.
Decided to implement all required API in #664.

**Comment by tatsuhiro-t** [comment]
We should decide how to implement HPACK related API.
Should we just expose nghttp2_hd_deflater and nghttp2_hd_inflater from nghttp2_session, and let application use HPACK API to extract information?
Or should we define wrapper function to keep them hidden?

Exposing these 2 objects are subject to the misuse.  Actually, we should only allow read-only functions, but our API does not enforce it at the moment.

**Comment by tatsuhiro-t** [comment]
I take the 2nd approach.  Handling misuse is harder for us.

**Comment by tatsuhiro-t** [comment]
@icing I think you are interested in this.  We have covered required fields in the current draft.

**Comment by icing** [comment]
Indeed, that is what I am using in ```mod_http2 v1.6.0``` apart from the HPACK which I do not expose. Great to see the adoption by the h2 server society!
